### ISSUE TITLE
Shouldn't this repo be called bl602-docs?

### ISSUE THREAD

**Issue by tchebb** [pine64/bl602-docs#2]
The chip is named BL602 (BL standing for Bouffalo Lab, I assume), not BLE602. There is no occurrence of "BLE602" anywhere in the vendor SDK. I assume the confusion came from its similarity to Bluetooth Low Energy.

I know renaming a repo after its been created is suboptimal, but I still think we should do it. It's only 9 hours old, so likely only a few people will have to change their remote URLs, and if we don't change it we'll be stuck with a confusing name forever.

**Comment by gamelaster** [comment]
Oh, sorry, my bad 😀 
Renaming isn't problem, Github automatically redirects the old url.
Fixed, thanks.
