### ISSUE TITLE
Directory layout is unclear

### ISSUE THREAD

**Issue by tchebb** [pine64/bl602-docs#3]
The layout of the Chinese and English HTML docs seems inconsistent, with the English ones at `/html` and the Chinese ones at `/docs/zh/html`. Additionally, having a folder called `docs` inside a repository explicitly for documentation seems redundant.

Here's my proposal for a directory structure:
- `sdk`: HTML/Sphinx documentation from the original SDK
  - `zh`: Original Chinese
    - `source`: Sphinx source
    - `html`: Rendered HTML
  - `en`: English translation
    - `source`: Sphinx source
    - `html`: Rendered HTML
- `mirrored`: Files available elsewhere online that we want to preserve, such as `BL602_BL604_DS_Datasheet.pdf`
- `reverse_engineered`: Docs written by community members, such as my `hardware_notes.md`
- `README.md`: Top-level docs README describing this directory structure, how to contribute, and related repos.

Thoughts?

**Comment by Avamander** [comment]
Working on it right now.

**Comment by Avamander** [comment]
Fixed most of the problems. I placed source Chinese documentation in the respective folder and the build output is in the correct location now.
