### ISSUE TITLE
Update Linux Starter Guide with 3rd party tool

### ISSUE THREAD

**Issue by username223** [pine64/bl602-docs#43]
The Linux Start Guide currently instructs the user to run the `BLFlashEnv` tool [which doesn't exist](https://github.com/pine64/bl_iot_sdk/issues/71).
The documentation also states that the `IO8` pin should be tied to `LOW`, while the `Pine64 BL602 EVB ver 1.1` board requires `IO8` to be tied to `HIGH` in order to flash.

I intend to replace the current guide with docs on how to build and flash the `sdk_app_helloworld` example.

Should the guide prefer any specific third party tool? Currently I only got [blflash](https://github.com/spacemeowx2/blflash) to work since [bl602tool](https://github.com/renzenicolai/bl602tool) requires the creation of the entire image manually, without any documentation for this process.

**Comment by gamelaster** [comment]
blflash is good. And BLFlashEnv exists, I added the lnik
