### ISSUE TITLE
Articles without any content at all should be removed

### ISSUE THREAD

**Issue by username223** [pine64/bl602-docs#50]
Several articles are completely empty except for a main header.

This leads to significant bloat in the documentation with titles that do not contain any useful information anyway.

One example is `Developer_Environment/openocd/`[openocd.rst](https://github.com/pine64/bl602-docs/blob/21e0f637347848fd9a5530d11b909a07eff07e65/src/en/Developer_Environment/openocd/openocd.rst#L1).

These files can be commented out in the `index.rst` file to remove them from the index, but this will produce the `WARNING: document isn't included in any toctree` error for each file. Ideally all the files should just be deleted and removed from the index, and any titles requiring body text should be added to an issue.

The full list of empty files is:
```
Developer_Environment/openocd/openocd.rst
Components/arch.rst
Components/Hal_drv/gpio.rst
Components/Middleware/bloop/bloop.rst
Components/Middleware/blsync/blsync.rst
Components/Middleware/security/security.rst
Components/Network/httpc/httpc.rst
Components/Network/https/https.rst
Components/Network/tls/tls.rst
Components/BLE/provision_WiFi/provision_WiFi.rst
Components/BLE/mesh/mesh.rst
```

Notice that GPIO has an entry in both `Components` and `Examples`. I'm unsure of the difference in content.

**Comment by tchebb** [comment]
Deleting all these makes sense to me.

**Comment by Avamander** [comment]
Some of these seem to me like they are a workaround to some bug with html generation. I'd check before removing if the resulting HTML is the same.

**Comment by username223** [comment]
> Some of these seem to me like they are a workaround to some bug with html generation. I'd check before removing if the resulting HTML is the same.

I'll take a look.

Some files (not listed above) do indeed attempt to `include` a file that does not exist, as described in issue https://github.com/pine64/bl602-docs/issues/46 and fixed in PR https://github.com/pine64/bl602-docs/pull/48, but I don't think any of the listed files attempt to do so.
